### ISSUE TITLE
DirtySprite in Pyscrollgroup is rendered but blendmode is being ignored

### ISSUE THREAD

**Issue by ri0t** [bitcraft/pyscroll#14]
Ahoi again, this time i'm having a little trouble adding fog of exploration.
It might be me doing things wrong again, but to illustrate, this is what i'm trying:

self.fog = pygame.sprite.DirtySprite()
self.fog.blendmode = pygame.BLEND_RGBA_MIN
self.fog.rect = pygame.Rect([0,0,self.render_size[0], self.render_size[1]])
self.fog.image = pygame.Surface([self.map_data.map_size[0]*self.map_data.tile_size[0], self.map_data.map_size[1]*self.map_data.tile_size[1]]).convert_alpha()
self.fog.image.fill((0,0,0, 255))
self.mapgroup.add(self.fog, layer=15)

I can now fill nice faded circles around the actor position and get an added non-transparent surface with the fog "seemingly lifted correctly".
Seems to me like the blendmode i set in the sprite is ignored.

**Comment by bitcraft** [comment]
Hello again, friend.  Yes, I am sure you are right.  I will look into it.   :smile:

**Comment by bitcraft** [comment]
I've pushed a new update, please pull the changes and try again.

**Comment by ri0t** [comment]
Omg, i updated to the new version in my virtualenv and now somehow inmidst of the code it throws an attribute-error that pygame.gfxdraw were unknown, suddenly :((

**Comment by bitcraft** [comment]
Thats odd...it should only attempt to use that if you are using shape drawing.

**Comment by ri0t** [comment]
Aah, you removed a direct "import python.gfxdraw", which i never did, but is necessary to set it up, once.. on to test the new blendmode =)

**Comment by ri0t** [comment]
Yup, thaaaat is sweeet! I have the nicest fog'o'exploration i could imagine. Now i just need to teach it how to obey walls.

**Comment by bitcraft** [comment]
I'd love to see a video of it sometime.  Glad it worked for you.
