### ISSUE TITLE
Animated character images.

### ISSUE THREAD

**Issue by Connor124** [bitcraft/pyscroll#16]
I doubt this is the place to ask for help but I couldn't find any way to contact you otherwise.

I recently began writing a top-down 2D RPG game using PyTMX and PyScroll. Most(if not all) of my code is your example code, so I thought you would be best to help me. 

My main problem is that your code doesn't blit the character image to the screen, instead it renders it as part of the display(I think), this method does not allow quick switching of the image which is needed for animation. 

View my repo here: https://github.com/Connor124/Gran-Theft-Crop-Toe

PS: I'm on Debian 9, Running Python3.5.2

**Comment by bitcraft** [comment]
Pyscroll renders everything to a buffer, including the sprites.  This give the best possible framerate.  If you want to animate your sprites, just change the sprite image periodically.  Set a timer somwhere or use an existing library for sprite animations.

**Comment by Connor124** [comment]
Ah, thank you. Sorry, I was busy. That doesn't help much, i'm pretty much a newbie, i'm only 13, I started using this module as it's really simple to get going. No need to help me anymore. 

Tuxemon is looking quite good though.

**Comment by Connor124** [comment]
`    def animation(self, direction, number):
        self.counter += 1
        if direction == "left":
            if number == 1:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 2:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 3:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 4:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 5:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 6:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 7:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 8:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')

**Comment by Connor124** [comment]
I worked it out. My code is below for anyone facing this problem also. Just make a call(?) to it in your main loop, and change direction variables depending on character movement direction. I'm sure this isn't the best way to do this.
    
    def animation(self, direction, number):
        self.counter += 1
        if direction == "left":
            if number == 1:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 2:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 3:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 4:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 5:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 6:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 7:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')
            if number == 8:
                self.hero = Hero('Tiles/character/walking_left/walking_left' +str(number) +'.png')

        if self.direction1 == "still" and self.direction2 == "still":
            if self.direction == "left":
                self.hero = Hero('Tiles/character/walking_left/walking_left1.png')
            if self.direction == "right":
                self.hero = Hero('Tiles/character/walking_right/walking_right1.png')
            if self.direction == "up":
                self.hero = Hero('Tiles/character/walking_up/walking_up1.png')
            if self.direction == "down":
                self.hero = Hero('Tiles/character/walking_down/walking_down1.png')

    self.group.remove(self)
    self.group.empty()
    self.group.add(self.hero)

**Comment by bitcraft** [comment]
> I'm sure this isn't the best way to do this.

but.... it works!  glad you got it figured out.
