### ISSUE TITLE
Tiles drawn incorrectly on right side of screen

### ISSUE THREAD

**Issue by namedtoaster** [bitcraft/pyscroll#17]
I created my own file called 'mygame.py' which is basically the same file as 'code/quest.py'. The only things that I changed were the tilemap files and a few other variables. The tilemap that I am using has two custom properties called start_tile_x/y. I use those values to determine the start location of the hero instead of putting him directly in the middle of the screen. Also, I set the window size to be the same dimensions as the tilemap file that I'm using.

When running the program, I move the hero to the right side of the screen but the map doesn't update properly. And it's just on the right portion of the tilemap (to the right of the cliff).
[v0.02.zip](https://github.com/bitcraft/pyscroll/files/450205/v0.02.zip)

**Comment by bitcraft** [comment]
Thanks for providing a zip file.  Unfortunately it is not enough to determine the exact cause.  I suspect that you do not have enough tiles.

> Pyscroll by default will not handle maps that are not completely filled with tiles. This is in consideration of drawing speed. To clarify, you can have several layers, some layers without tiles, and that is fine; the problem is when there are empty spaces in all the layers, leaving gaps in the entire map...

https://github.com/bitcraft/pyscroll#why-are-tiles-repeating-while-scrolling

For best performance, you must have tiles in each space of the map.  If you want, you can enable transparency (lower performance) or edit the map to include tiles in the empty spaces.  A simple way is simply add a colored tile.

**Comment by namedtoaster** [comment]
That fixed the problem. Coincidentally, I was creating a new tilemap with filled in spaces while I was waiting for the response. Thanks for being so speedy!
