### ISSUE TITLE
Jump physics/collision detection

### ISSUE THREAD

**Issue by namedtoaster** [bitcraft/pyscroll#18]
My collision detection is not working properly. In the update function, I go through the loop from the original code to detect collisions. That part is easy. The hard part is throwing in physics. The jump function itself is really quite simple, but trying to figure out all the cases and code them properly has proven to be a pain.

I'm not sure exactly how to move forward, but I just can't seem to figure this out. Some fresh eyes would be great.

[v0.02.zip](https://github.com/bitcraft/pyscroll/files/452583/v0.02.zip)

**Comment by bitcraft** [comment]
Hi named poster.  This issue isn't really related to pyscroll, as it doesn't handle physics.  I'd prefer to not discuss it here.  If you'd like to chat, you can reach me on IRC #pygame.
