### ISSUE TITLE
Large, full screen sprites get overdrawn by upper map tiles

### ISSUE THREAD

**Issue by bitcraft** [bitcraft/pyscroll#21]
For large sprites, like an overlay, the upper redrawn sprites when coalescing tiles will drawn over them.  There will need to be some check to make sure large sprites are drawn in the correct order.

**Comment by thomas64** [comment]
Here is the perfect small example for this bug:
https://github.com/thomas64/pyRPG_test2

**Comment by bitcraft** [comment]
fix was actually fairly trivial.  please test using your veil overlay and let me know if you still have this problem.  i was able to run the example you linked without the graphics glitch.

**Comment by thomas64** [comment]
It is definitely fixed! Thanks for your support!

**Comment by bitcraft** [comment]
@thomas64 I recently tweaked the way animated tiles are drawn.  I remember there was an issue with certain layers looking different, when compared to Tiled.  I think I may have completely fixed the issue.

**Comment by thomas64** [comment]
I still use pyscroll and PyTMX daily and from what I see now is that it looks good.
Thank you.
