### ISSUE TITLE
Problem with memory and PyscrollGroup

### ISSUE THREAD

**Issue by Anisa** [bitcraft/pyscroll#23]
Inside the pygame AbstractGroup there is a list which stores all removed sprites.
This list is cleared in the "draw" call of the pygame Group.

However, inside the PyscrollGroup which inherits and overrides the "draw" method, this list is never cleared. This will cause problems if you add and remove sprites to the group, as memory usage will constantly increase.

Attached zip file has a program (python3) which will reproduce the problem. In the file added we redraw a sprite every iteration of the main loop and it will print the time it takes to clear sprites every 5s.
This is of course a worst case scenario, but if you're utilizing the PyscrollGroup for a long time, then I can see the program running slower and slower as the list increases.

[reproduce.zip](https://github.com/bitcraft/pyscroll/files/966109/reproduce.zip)

**Comment by bitcraft** [comment]
Thanks for the report, I'll look into it.

**Comment by Anisa** [comment]
Added a pull request which fixes it
