### ISSUE TITLE
Slower load times since 2.16.14

### ISSUE THREAD

**Issue by bitcraft** [bitcraft/pyscroll#25]
Large maps now load much slower due to animation loading.  The method that pyscroll relies on to find tile locations is very slow, and seems unsuitable right now.

https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L532-L551

I'll keep this issue open to track progress on it.

**Comment by bitcraft** [comment]
18c4eb8c175a9525b6725db403966331c53c993f

may have fixed this issue.  loading speeds are similar to 2.16.12.  rendering speeds also seem similar, but i don't have very large maps to test with.

**Comment by thomas64** [comment]
But I do, and they now seems to load fast again.
