### ISSUE TITLE
Tutorial for animated maps with custom map data

### ISSUE THREAD

**Issue by BrettWitty** [bitcraft/pyscroll#27]
It's currently a little unclear what is required to implement/modify to enable animated maps for custom map data. Especially the relationship to ``AnimationToken``.

For static maps, it's straightforward to just hijack ``_get_tile_image`` and it works nicely.

**Comment by bitcraft** [comment]
Yes unfortunately there isn’t direct support for animated tiles for customs maps.  In order for it to work without TMX maps, you’ll need to implement a few methods of the data adapter class.  Those should be ‘reload_animations‘ and ‘get_animations’.  Because the implementation currently relies on each tile having a unique ID (gid) you’ll also need to implement a method to lookup by a unique ID (not part of the DataAdapter).  If you implement those methods, then the map will change the tiles correctly each time it is drawn.

**Comment by bitcraft** [comment]
I just updated pyscroll to make it a bit easier to implement animations for custom maps.  You'll need to implement the following:

https://github.com/bitcraft/pyscroll/blob/master/pyscroll/data.py#L214-L222

https://github.com/bitcraft/pyscroll/blob/master/pyscroll/data.py#L234-L250

Don't worry about the AnimationFrame class; its for internal use only.  Just implement those two methods in a way that suits your maps and it should work fine.

**Comment by BrettWitty** [comment]
That's great. I think the only thing missing is updating the AnimatedToken positions. I managed to overwrite `get_tile_images_by_rect` to mimic the version in `TiledMapData`:

```python
def get_tile_images_by_rect(self, rect):
    """ Given a 2d area, return generator of tile images inside
    Given the coordinates, yield the following tuple for each tile:
      X, Y, Layer Number, pygame Surface
    This method also defines render order by re arranging the
    positions of each tile as it is yielded to the renderer.
    There is an optimization that you can make for your data:
    If you can provide access to tile information in a batch,
    then pyscroll can access data faster and render quicker.
    To implement this optimization, override this method.
    Not like python 'Range': should include the end index!
    :param rect: a rect-like object that defines tiles to draw
    :return: generator
    """

    from pyscroll import rect_to_bb
    from itertools import product

    x1, y1, x2, y2 = rect_to_bb(rect)

    track = bool(self._animation_queue)

    for layer in self.visible_tile_layers:

        for y, x in product(range(y1, y2 + 1),
                            range(x1, x2 + 1)):

            gid = self._render_data[x,y]

            if track and gid in self._tracked_gids:
                self._animation_map[gid].positions.add((x,y,layer))

            tile = self.get_tile_image(x, y, layer)
            if tile:
                yield x, y, layer, tile
```

My `_render_data` contains a universal GID for a sprite (or a stand-in for a spritesheet for animation), per map position.

Overall I just had to modify `_get_tile_image_by_id`, `_get_tile_image`, and `get_animations` to get my custom data class working, just in case anyone else is trying this.

**Comment by BrettWitty** [comment]
Yep, and I'm getting a nice framerate. Thanks for the library!
