### ISSUE TITLE
KeyError: 'path'

### ISSUE THREAD

**Issue by baronyoung** [bitcraft/pyscroll#31]
I'm running Python 3.7 on Linux and I get the following error when trying to run Quest.py.  I'm running it from within a Pycharm project I've created.  I've also tried outside Pycharm from a shell.  I extracted the files from the downloaded zip from GitHub but did not keep the same root directory.  Can't see why that would matter looking at the code.  Any ideas?  

> Traceback (most recent call last):
>   File "/home/xxx/data/pycharm/xxx/tutorial/quest.py", line 240, in <module>
>     game = QuestGame()
>   File "/home/xxx/data/pycharm/xxx/tutorial/quest.py", line 109, in __init__
>     tmx_data = load_pygame(self.filename)
>   File "/home/xxx/.virtualenvs/xxx/lib/python3.7/site-packages/pytmx/util_pygame.py", line 141, in load_pygame
>     return pytmx.TiledMap(filename, *args, **kwargs)
>   File "/home/xxx/.virtualenvs/xxx/lib/python3.7/site-packages/pytmx/pytmx.py", line 360, in __init__
>     self.parse_xml(ElementTree.parse(self.filename).getroot())
>   File "/home/xxx/.virtualenvs/xxx/lib/python3.7/site-packages/pytmx/pytmx.py", line 400, in parse_xml
>     self.add_tileset(TiledTileset(self, subnode))
>   File "/home/xxx/.virtualenvs/xxx/lib/python3.7/site-packages/pytmx/pytmx.py", line 845, in __init__
>     self.parse_xml(node)
>   File "/home/xxx/.virtualenvs/xxx/lib/python3.7/site-packages/pytmx/pytmx.py", line 894, in parse_xml
>     p["path"] = os.path.join(os.path.dirname(source), p["path"])
> KeyError: 'path'

**Comment by macskay** [comment]
@bitcraft : I suppose this is more of a problem with bitcraft/PyTmx rather than bitcraft/pyscroll. Maybe this issue should be moved over there.
