### ISSUE TITLE
Pygame 2 and tutorial tile alpha support

### ISSUE THREAD

**Issue by ambv** [bitcraft/pyscroll#36]
I'm a beginner in terms of `pygame` so I can't tell if this is something easy or tricky to fix. I noticed that the quest tutorial project doesn't render alpha correctly for some of the tiles (but not all, see the lakes for example).

<img width="912" alt="Screenshot 2020-11-02 at 14 26 21" src="https://user-images.githubusercontent.com/55281/97873082-6623af00-1d17-11eb-9e1e-93209e6247bd.png">

Do you know what needs to change for this to look correctly with pygame 2.0?

**Comment by bitcraft** [comment]
Thanks for pointing that out.  Is this pygame 2.0?  I haven’t tested with
it yet.  There were some issues with it in the past.  Mac OS also seems to
have weird regressions too.  Please let me know.  Shouldn’t be a hard fix,
likely the alpha detection is wrong.

**Comment by bitcraft** [comment]
i guess there was some regression between pygame1/2 and how pytmx was handling colorkey images, like some of the tiles on this map.  the issues was in pytmx, which i've made a fix for and pushed.  please update pytmx amd try again.  tested with python3.9 and pygame2 on fedora33.

**Comment by ambv** [comment]
Aww yiss, it's fixed! Thank you for your fantastic turnover.

<img width="912" alt="Screenshot 2020-11-02 at 17 36 27" src="https://user-images.githubusercontent.com/55281/97893747-fbcc3800-1d31-11eb-911b-5573e6e184e3.png">
