### ISSUE TITLE
Querying pyscroll for a sprite's position?

### ISSUE THREAD

**Issue by joereynolds** [bitcraft/pyscroll#39]
Hello again!

I'm wanting to add in a basic lighting system into my game. The gist of it is that I want certain tiles to be illuminated. The problem comes with rendering the light at that tiles position. After pyscroll has done its zooming and possibly scrolling, the `rect`'s `x` and `y` that I am querying are incorrect.

Here is some code that I'm working with to give you an idea:

```
def render_lights(self):
        self.veil.fill((50,50,50,155))

        # light_sources is just a slice of some of the sprites out of a PyscrollGroup
        for light_source in self.light_sources:
            light = pygame.image.load('./data/light-soft.png')
            self.veil.blit(
                light, 
                (
                    light_source.rect.x,
                    light_source.rect.y
                )
            )

        #To debug, remove the special_flags arg
        # needs blend_mult flag to work
        self.game_area.blit(self.veil, (0,0), )
```

I basically need to pin the light source to the tile but since the tiles can (and do) scroll, I was wondering what methods are available (if any) to do this?

Thanks again!

**Comment by bitcraft** [comment]
this should work for you
https://github.com/bitcraft/pyscroll/blob/master/pyscroll/orthographic.py#L246
```python
    def translate_point(self, point):
        """ Translate world coordinates and return screen coordinates.  Respects zoom level
        Will be returned as tuple.
        :rtype: tuple
        """
```

**Comment by bitcraft** [comment]
you could also make the lights sprites.  set `Sprite.blendmode` and pyscroll will use the when blitting.  
https://github.com/bitcraft/pyscroll/blob/master/pyscroll/group.py#L52

**Comment by joereynolds** [comment]
That's much nicer. I'm also using pytmx, does that mean I could define the light sprite in Tiled and then use it from there?

**Comment by bitcraft** [comment]
you could have a "LightSprite" class or something.  when loading the level, create them for all your static lights...maybe set their type in tiled so they can be identified.  also create one for the player and each frame move it to be over the player sprite before drawing the screen.

**Comment by joereynolds** [comment]
That `translate_point` method mostly did the trick, It doesn't exactly follow it (it's quite close) but I think this is because my tiles are being zoomed in to a stretched width/height (.i.e. a resolution of 800x480 doesn't divide evenly for 32x32 tiles) . I'll investigate that myself, thanks for the help!
