### ISSUE TITLE
Make use of the TiledMapData.visible_tile_layers property

### ISSUE THREAD

**Issue by nmfm** [bitcraft/pyscroll#41]
Shouldn't `self.visible_tile_layers` be used here instead of `self.tmx.visible_tile_layers`? 

https://github.com/bitcraft/pyscroll/blob/master/pyscroll/data.py#L389

Otherwise, what's the point of overriding that method in a subclass?

Thanks

**Comment by bitcraft** [comment]
That is a DataAdapter class and is meant to operate directly on TMX data.
