### ISSUE TITLE
Transparent map background where map is empty

### ISSUE THREAD

**Issue by ri0t** [bitcraft/pyscroll#9]
I'd like to render some background surface behind the map with alpha of the top layers used - how to do that?

**Comment by bitcraft** [comment]
You ushould be able to do it by passing 'alpha=true' to the BufferedRenderer.


# Make data source for the map
map_data = pyscroll.TiledMapData(tmx_data)

# Make the scrolling layer
screen_size = (400, 400)
map_layer = pyscroll.BufferedRenderer(map_data, screen_size, alpha=true)

# make the PyGame SpriteGroup with a scrolling map
group = pyscroll.PyscrollGroup(map_layer=map_layer)

First, draw your background, then draw the group.  As I remember, there are performance issues with this, so make sure to convert your background surface first.  Let me know how it goes...I don't test the alpha feature often.

**Comment by ri0t** [comment]
Aah. Sorry, i could've found that out myself. It works like a charm.
Thanks again for your quick help =) :+1:
